microsoft/OAT

LogicalAnalyzer.Tests/LogicalAnalyzer.Tests.csproj, LogicalAnalyzer.Tests/VehicleDemo.cs, LogicalAnalyzer/Analyzer.cs, README.md
=> Add Tolling Demo

OAT.Tests/ExpressionsTests.cs, OAT.Tests/OperationsTests.cs, OAT.Tests/VehicleDemo.cs, OAT/Analyzer.cs, OAT/Clause.cs, OAT/Logger.cs, OAT/OAT.csproj, OAT/Rule.cs, OAT/Strings.cs, Pipelines/core-pipeline.yml
Some improvements from Roslynator and Sharpen and running code cleanup.
Implements "Invert" functionality for clauses.
=> Code Cleanup

OAT/Clause.cs, OAT/Operation.cs, OAT/Operations/ContainsOperation.cs, OAT/Operations/RegexOperation.cs
Adds options for IgnoreCase and MultiLine regexes using new Arguments field in Clause.
Required for DevSkim/ApplicationInspector.
=> Add argument support to regex

.github/workflows/publish-wasm-to-gh-pages.yml, OAT.Blazor/wwwroot/index.html, OAT.sln
Release builds aren't working with trimming.
=> Temporarily build debug instead of release

OAT.Blazor/Components/LoadedAssemblies.razor, OAT.Blazor/Pages/Author.razor, OAT.Tests/ReflectionHelpersTests.cs, OAT.Tests/TestObject.cs, OAT.sln, OAT/Helpers.cs
Add Tests for new Reflections helps functionality.
=> Show Loaded Assemblies in WASM + Add Dictionary and List crawling for Reflection Helpers

.github/workflows/codeql-analysis.yml
=> Fix CodeQL Scanning

.github/workflows/codeql-analysis.yml, Directory.Build.props, OAT.Benchmarks/OAT.Benchmarks.csproj, OAT.Blazor.Components/OAT.Blazor.Components.csproj, OAT.Blazor/OAT.Blazor.csproj, OAT.Tests/OAT.Tests.csproj, OAT/OAT.csproj, VehicleDemo/VehicleDemo.csproj
Bump nbgv to fix codeql workflow error re: GitHub Actions set-env changes
=> Bump NBGV to Fix CodeQL Workflow

OAT.Tests/HelpersTest.cs, OAT/Helpers.cs
Also fix bug in ConstructedOfLoadedTypes
=> Bring back Constructed of basic types

OAT/Analyzer.cs, OAT/Microsoft/CST/OAT/AnalyzerOptions.cs
Option being made available for dependent libraries which already have a parallel loop around the analysis and prefer single threaded analysis.  Default remains parallelized.
=> Adds a single threaded option to analysis.

OAT.Blazor.Components/Inputs/DictionaryStringObject.razor, OAT.Blazor.Components/Inputs/ListObjectInput.razor, OAT.Blazor.Components/Inputs/ObjectInput.razor, OAT.Blazor.Components/Inputs/PropertyInput.razor, OAT.Blazor/Pages/DemoSandbox.razor, OAT/Helpers.cs
=> Adds OAT Component for String Keyed Dictionaries

OAT.Blazor.Components/Inputs/DictionaryObjectObject.razor, OAT.Blazor.Components/Inputs/DictionaryStringObject.razor, OAT.Blazor.Components/Inputs/ObjectInput.razor, OAT.Blazor.Components/Inputs/PropertyInput.razor, OAT.Blazor.Components/Inputs/TupleInput.razor, OAT.Blazor/wwwroot/css/app.css, OAT/Helpers.cs
=> Adds DictionaryObjectObject and Tuple inputs

OAT.Blazor.Components/Inputs/ClauseInput.razor, OAT.Blazor.Components/Inputs/DictionaryObjectObject.razor, OAT.Blazor.Components/Inputs/DictionaryStringListStringInput.razor, OAT.Blazor.Components/Inputs/DictionaryStringStringInput.razor, OAT.Blazor/Pages/Author.razor, OAT/Analyzer.cs
OAT.Blazor still uses it but is not pulled in as a package anywhere else.
=> Remove Newtonsoft dependency from OAT.

OAT.Blazor.Components/Inputs/DictionaryObjectObject.razor, OAT.Blazor.Components/Inputs/ListObjectInput.razor, OAT.Blazor.Components/Inputs/PropertyInput.razor, OAT/Helpers.cs
ListObjectInput mistakenly only supported generic ILists and not arrays.
=> Fix ListObjectinput to properlyget the type of arrays

OAT.Blazor/Pages/Author.razor, OAT.Blazor/Pages/DemoSandbox.razor, OAT.Blazor/Pages/Sandbox.razor, OAT.Blazor/Properties/launchSettings.json, OAT.Blazor/wwwroot/index.html, OAT/Analyzer.cs, OAT/Helpers.cs, OAT/Operations/EndsWithOperation.cs, OAT/Operations/IsAfterOperation.cs, OAT/Operations/LessThanOperation.cs, OAT/Operations/ScriptOperation.cs, OAT/Operations/StartsWithOperation.cs
Also CodeQL suggestions from LGTM.
=> Fix Blazor

.github/workflows/codeql-analysis.yml, .github/workflows/publish-wasm-and-docs-to-gh-pages.yml, Directory.Build.props, OAT.Benchmarks/OAT.Benchmarks.csproj, OAT.Blazor.Components/Inputs/PropertyInput.razor, OAT.Blazor.Components/OAT.Blazor.Components.csproj, OAT.Blazor/App.razor, OAT.Blazor/OAT.Blazor.csproj, OAT.Blazor/Properties/launchSettings.json, OAT.Blazor/wwwroot/service-worker.published.js, OAT.Tests/OAT.Tests.csproj, OAT.sln, OAT/Helpers.cs, OAT/NullabilityExtensions.cs, OAT/OAT.csproj, Pipelines/core-pipeline.yml, Pipelines/templates/dotnet-test-job.yml, Pipelines/templates/nuget-build-job.yml, README.md, VehicleDemo/VehicleDemo.csproj, VehicleDemo/VehicleDemoClasses.cs
=> Bump to .NET 6

OAT.Blazor.Components/OAT.Blazor.Components.csproj, OAT.Blazor/OAT.Blazor.csproj, OAT/ScriptData.cs
Combine all the dependabot changes into one PR.
=> Bump Dependencies

Directory.Build.props, OAT.Blazor.Components/OAT.Blazor.Components.csproj, OAT.Blazor/OAT.Blazor.csproj, OAT.Scripting/OAT.Scripting.csproj, OAT.Tests/OAT.Tests.csproj, OAT/OAT.csproj
Updates dependencies, and enables dotnet reproducible builds. https://github.com/dotnet/reproducible-builds
=> Update Dependencies, Enable Reproducible Builds

Pipelines/oat-release.yml
This PR brings back the release stage with the version of signing task. 
Note that this does not yet include publishing to NuGet.
=> add release stage with new signing

Directory.Build.props, OAT.Benchmarks/OAT.Benchmarks.csproj, OAT.Tests/CaptureTests.cs, OAT.Tests/ExpressionsTests.cs, OAT.Tests/GlobalSetup.cs, OAT.Tests/HelpersTest.cs, OAT.Tests/LambdaTests.cs, OAT.Tests/OAT.Tests.csproj, OAT.Tests/OperationsTests.cs, OAT.Tests/ReflectionHelpersTests.cs, OAT.Tests/VehicleDemo.cs, Pipelines/oat-pr.yml, Pipelines/oat-release.yml
Some extra work is required if you want coverage and trx report but I need the template to be updated.
=> Use MSTest runner instead of VSTest

Pipelines/oat-release.yml
use templates from twcsecurityassurance rather than duplicating in twcdot
=> release pipeline should use same templates as PR pipeline
